# Generated by Django 2.1 on 2019-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('answer_5', models.CharField(max_length=200)),
                ('answer_6', models.CharField(max_length=200)),
                ('answer_7', models.CharField(max_length=200)),
                ('answer_8', models.CharField(max_length=200)),
                ('answer_9', models.CharField(max_length=200)),
                ('answer_10', models.CharField(max_length=200)),
            ],
        ),
    ]
