# Generated by Django 2.1 on 2019-12-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='answer_1',
            new_name='HUMIDITY',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='answer_10',
            new_name='OUTLOOK',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='answer_2',
            new_name='PLAY',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='answer_3',
            new_name='TEMPERATURE',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='answer_4',
            new_name='WINDY',
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer_6',
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer_7',
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer_8',
        ),
        migrations.RemoveField(
            model_name='results',
            name='answer_9',
        ),
    ]
